version: '2'

volumes:
  cassandra-data:
    external: true

services:
  cassandra:
    container_name: cassandra-single
    image: cassandra:3.7
    user: cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra/
    ports:
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication if SSL is enabled
      - "9042:9042" # native protocol clients
      - "7199:7199" # JMX
      - "9160:9160" # the deprecated Thrift interface